language: node_js
node_js: stable
before_install:
  - composer config --global github-oauth.github.com $GITHUB_TOKEN
cache:
  directories:
    - node_modules
install: 
  - yarn install
script:
  - yarn run build
  - cp -r ./build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
