language: node_js
node_js: stable
script: 
  - npm ci
  - npm run build
  - cp -r ./build/*
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master